-- MySQL Script generated by MySQL Workbench
-- 06/19/16 13:15:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_countable
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_countable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_countable` DEFAULT CHARACTER SET utf8 ;
USE `db_countable` ;

-- -----------------------------------------------------
-- Table `db_countable`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_countable`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_countable`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_countable`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_countable`.`subcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_countable`.`subcategory` (
  `subcategory_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `ref_category` INT NOT NULL,
  PRIMARY KEY (`subcategory_id`),
  INDEX `subcategory_ref_category_idx` (`ref_category` ASC),
  CONSTRAINT `subcategory_ref_category`
    FOREIGN KEY (`ref_category`)
    REFERENCES `db_countable`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_countable`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_countable`.`transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(8,2) NOT NULL,
  `is_deposit` TINYINT(1) NULL,
  `is_reconcilied` TINYINT(1) NULL,
  `date` DATETIME NULL,
  `description` VARCHAR(500) NULL,
  `ref_account` INT NOT NULL,
  `ref_subcategory` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `transaction_ref_account_idx` (`ref_account` ASC),
  INDEX `transaction_ref_subcategory_idx` (`ref_subcategory` ASC),
  CONSTRAINT `transaction_ref_account`
    FOREIGN KEY (`ref_account`)
    REFERENCES `db_countable`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `transaction_ref_subcategory`
    FOREIGN KEY (`ref_subcategory`)
    REFERENCES `db_countable`.`subcategory` (`subcategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
